version: '3.4'
networks:
  constr-sw-2022-2:
volumes:
  keycloak-data:
    external: true
  mongodb-data:
    external: true
services:
  keycloak:
    container_name: keycloak
    image: jboss/keycloak:latest
    ports:
      - 8080:8080
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=a12345678
    volumes:
      - keycloak-data:/opt/jboss/keycloak/standalone/data
    networks:
      - constr-sw-2022-2
  keycloak_api:
    container_name: keycloak_api
    build: ./keycloak
    ports:
      - 3000:3000
    environment:
      - KEYCLOAK_HOST=host.docker.internal
      - KEYCLOAK_PORT=8080
      - API_PORT=3000
      - REALM_NAME=constr-sw-2022-2
      - CLIENT_SECRET=BzXf20nFQCTPgpkekx3XHt2yOygLXj23
    networks:
      - constr-sw-2022-2
    depends_on:
      - keycloak
  mongo:
    container_name: mongo
    image: mongo:latest
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=a12345678
    volumes:
      - mongodb-data:/data/mongodb
    networks:
      - constr-sw-2022-2
  disciplinas:
    container_name: disciplines
    build: ./disciplines
    ports:
      - 8086:8086
    environment:
      - KEYCLOAK_API_HOST=host.docker.internal
      - KEYCLOAK_API_PORT=3000
      - MONGODB_HOST=mongo
      - MONGODB_PORT=27017
      - MONGODB_USER=admin
      - MONGODB_PASSWORD=a12345678
      - API_PORT=8086
    networks:
      - constr-sw-2022-2
    depends_on:
      - keycloak_api
      - mongodb
  # {api}-api:
    # container-name: {api}-api
    # ...
    # depends_on:
    #   - keycloak-api
    #   - mongodb OU postgresql
  # grupo1
  # predios-api:
      # ports:
      #   - 8081:???
  # grupo2
  # recursos-api:
      # ports:
      #   - 8082:???
  # grupo3
  # reservas-api:
    # container-name: {api}-api
    # ...
      # ports:
      #   - 8083:???
    # depends_on:
    #   - keycloak-api
    #   - mongodb OU postgresql
    #   - recursos-api
  # grupo5
  # turmas-api:
      # ports:
      #   - 8085:???
  # grupo6
  # disciplinas-api:
      # ports:
      #   - 8086:???
  # grupo7
  # aulas-api:
      # ports:
      #   - 8087:???