version: "3.4"
networks:
  constr-sw-2022-2:
volumes:
  keycloak-data:
    external: false
services:
  keycloak:
    container_name: keycloak
    image: jboss/keycloak:latest
    ports:
      - 8080:8080
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=a12345678
    volumes:
      - keycloak-data:/opt/jboss/keycloak/standalone/data
    networks:
      - constr-sw-2022-2
  keycloak-api:
    depends_on:
      - keycloak
  disciplinas-api:
    depends_on:
      - mongo 
      - keycloak
    build: ./
    image: disciplinas:latest
    environment:
      NODE_ENV: production
      MONGO_URL: mongo
    ports:
      - 3333:3333
    networks:
      - constr-sw-2022-2
    restart: unless-stopped
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    volumes:
      - mongodb_volume:/home/mongodb
      - mongodb_data_volume:/data/db
    networks:
      - mongo-compose-network
    restart: unless-stopped   